name: GitHub Actions Secrets

on:
  workflow_dispatch:

jobs:
  deployment:
    runs-on: ubuntu-latest
    steps:
      - name: 'List GitHub Actions Secrets'
        run: |
          echo "MY_SECRET: ${{ secrets.MY_SECRET }}"
          echo "SECRET_TWO: ${{ secrets.SECRET_TWO }}"

      - name: 'List Secret as an Environment Variable'
        run: |
          echo "MY_SECRET: $MY_SECRET"
        env:
          AZURE_CRED: ${{ secrets.MY_SECRET }}
