name: Artifacts Demo

on: push

jobs:
  job_1:
    name: 'Upload Artifact'
    runs-on: ubuntu-latest
    steps:
      - name: "Create a file"
        run: |
          echo "This is a file for the artifact" > file.txt

      - uses: actions/upload-artifact@v4
        with:
          name: file
          path: file.txt
          retention-days: 1

  job_2:
    name: 'Download Artifact'
    runs-on: ubuntu-latest
    needs: job_1
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: file
      - run: cat file.txt
 