name: Passing Velues to Next Steps

on: workflow_dispatch

jobs:
    passing_values_bw_steps:
        runs-on: ubuntu-latest

        steps:
            -   name: 'Set the value'
                id: step_one
                run: |
                    echo "variableName=value" >> $GITHUB_ENV

            -   name: 'Create-Variables'
                id: var_source_step
                run: |
                    echo "Performing a random task"
                    echo "var1_name=var1_value" >> $GITHUB_ENV
                    echo "var2_date=$(date + '%Y-%m-%d-%H-%M-%S')" >> $GITHUB_ENV

            -   name: 'Use the value'
                id: step_three
                run: |
                    echo "Printing the values"
                    echo "variableName: ${{ env.variableName }}"
                    echo "The value of var1_name is ${{ steps.var_source_step.outputs.var1_name }}"
                    echo "The value of var2_date is ${{ steps.var_source_step.outputs.var2_date }}"
