name: 'Passing Values Between Jobs'

on:
  workflow_dispatch:

jobs:
    job1:
        runs-on: ubuntu-latest

        outputs:
            output_one: ${{ steps.step_one.outputs.test }}
            output_two: ${{ steps.step_two.outputs.test }}

        steps:
            -   id: step_one
                run: echo "test=value1" >> $GITHUB_ENV
            -   id: step_two
                run: echo "test=value2" >> $GITHUB_ENV

    job2:
        runs-on: ubuntu-latest
        needs: job1
        steps:
            -   name: 'Use the value'
                run: |
                    echo "Printing the values"
                    echo "The value of test is ${{ needs.job1.outputs.output_one }}"
                    echo "The value of test is ${{ needs.job1.outputs.output_two }}"